//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusBets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bet_Tiket
    {
        public string Id_Tiket { get; set; }
        public string Id_Ev { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Potential_Win { get; set; }
        public Nullable<double> Total_Odd { get; set; }
    
        public virtual Events Events { get; set; }
    }
}
