//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusBets.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CampusBetsEntities1 : DbContext
    {
        public CampusBetsEntities1()
            : base("name=CampusBetsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bet_Tiket> Bet_Tiket { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<Tip_Event> Tip_Event { get; set; }
    }
}
